version: 2
jobs:
  build:
    working_directory: /go/src/github.com/oinume/algo
    docker:
      - image: golang:1.12-stretch
        environment:
          - GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Set .gitconfig"
          command: |
            echo "" > ~/.gitconfig
            git config --global url."https://github.com".insteadOf git://github.com
            git config --global http.https://gopkg.in.followRedirects true
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: "Install dependencies"
          command: |
            go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Install lint tools"
          command: |
            make bootstrap-lint-tools
      - run:
          name: "Run lint"
          command: make lint
      - run:
          name: "Run go test"
          command: |
            go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run:
          name: "Upload to codecov"
          command: |
            bash <(curl -s https://codecov.io/bash)
